spring:
  application:
    name: authoring-service
  data:
    mongodb:
      host: authoring-db
      username: user
      password: password
      database: survey
      port: 27017
  rabbitmq:
    host: rabbitmq
  sleuth:
    sampler:
      percentage: 1

# (2017-09-02) As of Spring Cloud Finchley.M2+ certain auto-config and config don't work, so disable!
# E.g., we get java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/Endpoint
# or java.lang.NoClassDefFoundError: org/springframework/boot/autoconfigure/web/servlet/error/ErrorController
# Also @see https://github.com/spring-projects/spring-boot/issues/10306

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      - org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration
      - org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration
      - org.springframework.cloud.netflix.hystrix.HystrixAutoConfiguration
      - org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration
      - org.springframework.cloud.sleuth.metric.TraceMetricsAutoConfiguration
      - org.springframework.cloud.sleuth.instrument.web.TraceWebServletAutoConfiguration
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

server:
  context-path: /authoring/
  port: 7878
logging:
  level:
    com.draganlj.survey: DEBUG

api:
  version: 1.0